# TFLM 1.3.5 passes zero filter channels to ESP-NN 1.3.2. Generate the
# two-line correction in build/, without modifying the component cache.
function(xiaotai_fix_conv_channels target component_dir output_dir)
    set(source "${component_dir}/tensorflow/lite/micro/kernels/esp_nn/conv.cc")
    file(SHA256 "${source}" source_hash)
    if(NOT source_hash STREQUAL "d5cf0ecaee5b6d8b7f141be364c85beab42a0f72bec8e230e2e69d8f605ea42d")
        message(FATAL_ERROR "TFLM conv.cc changed; review the P4 filter-channel fix before upgrading")
    endif()
    file(READ "${source}" contents)
    set(before ".channels = 0, .extra = 0")
    string(REGEX MATCHALL "\\.channels = 0, \\.extra = 0" matches "${contents}")
    list(LENGTH matches match_count)
    if(NOT match_count EQUAL 2)
        message(FATAL_ERROR "Expected both Prepare and Eval filter-channel assignments")
    endif()
    string(REPLACE "${before}" ".channels = filter->dims->data[3], .extra = 0"
        corrected "${contents}")
    set(output "${output_dir}/conv.cc")
    file(MAKE_DIRECTORY "${output_dir}")
    # The component lives in another CMake directory: materialize before its
    # source validation, and preserve mtime when reconfiguring unchanged code.
    if(EXISTS "${output}")
        file(READ "${output}" existing)
    endif()
    if(NOT EXISTS "${output}" OR NOT existing STREQUAL corrected)
        file(WRITE "${output}" "${corrected}")
    endif()
    get_target_property(sources ${target} SOURCES)
    list(FIND sources "${source}" index)
    if(index EQUAL -1)
        message(FATAL_ERROR "TFLM target no longer compiles the expected ESP-NN convolution")
    endif()
    list(REMOVE_AT sources ${index})
    list(INSERT sources ${index} "${output}")
    set_property(TARGET ${target} PROPERTY SOURCES "${sources}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
    message(STATUS "P4 TFLM: filter channels corrected in Prepare and Eval (cache unchanged)")
endfunction()
