#!/usr/bin/env python3
"""Convert the supplied PNG to the S3 shortcut. Requires Pillow, not a build step."""

from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
COMPONENT = ROOT / "components" / "starter_product"
SOURCE = COMPONENT / "assets" / "phone_shortcut.png"
OUTPUT = COMPONENT / "src" / "starter_product_s3_phone.inc"
SIZE = (44, 44)


def main() -> None:
    with Image.open(SOURCE) as source:
        image = ImageOps.fit(source.convert("RGBA"), SIZE, Image.Resampling.LANCZOS)
    data = bytearray()
    pixels = image.load()
    for y in range(image.height):
        for x in range(image.width):
            red, green, blue, alpha = pixels[x, y]
            rgb565 = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
            data.extend((rgb565 >> 8, rgb565 & 0xFF, alpha))

    lines = [
        "/* Generated by tools/generate_phone_shortcut.py from assets/phone_shortcut.png.",
        " * RGB565 (byte-swapped) + alpha; immutable pixels stay in flash. */",
        "#if LV_COLOR_DEPTH != 16 || !LV_COLOR_16_SWAP",
        '#error "S3 phone shortcut requires the configured byte-swapped RGB565 format"',
        "#endif",
        "",
        "static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t s3_phone_shortcut_pixels[] = {",
    ]
    for offset in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 24]) + ",")
    lines.extend([
        "};",
        "",
        "static const lv_img_dsc_t s3_phone_shortcut_image = {",
        "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        f"    .header.w = {SIZE[0]},",
        f"    .header.h = {SIZE[1]},",
        "    .data_size = sizeof(s3_phone_shortcut_pixels),",
        "    .data = s3_phone_shortcut_pixels,",
        "};",
        "",
    ])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
