#!/usr/bin/env bash
set -euo pipefail
project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python3 "$project_dir/tools/test_build_policies.py"
python3 "$project_dir/tools/test_voice_reliability.py"
python3 "$project_dir/tools/test_release_assets.py"
python3 "$project_dir/tools/test_captive_portal_contract.py"
python3 "$project_dir/tools/test_station_identity.py"
python3 "$project_dir/tools/test_binding_prompt_cancel.py"
python3 "$project_dir/tools/test_playout.py"
python3 "$project_dir/tools/test_wifi_manual_disconnect.py"
python3 "$project_dir/tools/test_offline_onboarding.py"
python3 "$project_dir/tools/test_voip_task_cleanup.py"
python3 "$project_dir/tools/test_call_room_recovery.py"
python3 "$project_dir/tools/test_contact_entry.py"
python3 "$project_dir/tools/test_contact_query.py"
python3 "$project_dir/tools/test_screen_event_lifetime.py"
bash "$project_dir/tools/test_audio_resampler.sh"
python3 "$project_dir/tools/test_audio_only.py"
python3 "$project_dir/tools/test_media_platform_contract.py"
python3 "$project_dir/tools/test_audio_boot_gain.py"
