# Build-local namespacing of the locked cJSON implementation. Do not change
# global cJSON hooks: the SDK/platform also use them on other tasks.
function(starter_room_json_headers cjson_dir output_dir)
    file(STRINGS "${cjson_dir}/cJSON.h" declarations REGEX "^CJSON_PUBLIC")
    set(prefix "")
    set(unprefix "")
    set(prototypes "")
    foreach(declaration IN LISTS declarations)
        string(REGEX MATCH "(cJSON_[A-Za-z0-9_]+)\\(" api "${declaration}")
        if(NOT api)
            message(FATAL_ERROR "Unrecognized cJSON public declaration: ${declaration}")
        endif()
        set(name "${CMAKE_MATCH_1}")
        string(APPEND prefix "#define ${name} room_json_${name}\n")
        string(APPEND unprefix "#undef ${name}\n")
        string(APPEND prototypes "${declaration}\n")
        list(APPEND names "${name}")
    endforeach()
    # cJSON also exports a recursion helper absent from its public header.
    file(STRINGS "${cjson_dir}/cJSON.c" definitions REGEX "^(CJSON_PUBLIC|cJSON [*])")
    foreach(definition IN LISTS definitions)
        string(REGEX MATCH "(cJSON_[A-Za-z0-9_]+)\\(" api "${definition}")
        set(name "${CMAKE_MATCH_1}")
        if(api AND NOT name IN_LIST names)
            string(APPEND prefix "#define ${name} room_json_${name}\n")
            string(APPEND unprefix "#undef ${name}\n")
            list(APPEND names "${name}")
        endif()
    endforeach()
    file(WRITE "${output_dir}/room_json_prefix.h" "${prefix}")
    file(WRITE "${output_dir}/room_json_unprefix.h" "${unprefix}")
    file(WRITE "${output_dir}/room_json_declarations.h"
        "#include \"room_json_prefix.h\"\n${prototypes}#include \"room_json_unprefix.h\"\n")
endfunction()
