#pragma once

/* ESP32-P4 480x320 device-console visual tokens. */
#define DISPLAY_UI_COLOR_PAGE_BG       0xF3F8FB
#define DISPLAY_UI_COLOR_SURFACE       0xFFFFFF
#define DISPLAY_UI_COLOR_SURFACE_SOFT  0xF7FBFF
#define DISPLAY_UI_COLOR_TEXT          0x10243E
#define DISPLAY_UI_COLOR_TEXT_MUTED    0x64758A
#define DISPLAY_UI_COLOR_BORDER        0xD5E0EB
#define DISPLAY_UI_COLOR_BORDER_STRONG 0xB9C8D4
#define DISPLAY_UI_COLOR_BLUE          0x1296DB
#define DISPLAY_UI_COLOR_BLUE_DARK     0x1768B7
#define DISPLAY_UI_COLOR_GREEN         0x20BF7A
#define DISPLAY_UI_COLOR_RED           0xF6494C
#define DISPLAY_UI_COLOR_AMBER         0xF5A20A
#define DISPLAY_UI_COLOR_TEAL          0x009D9A

#define DISPLAY_UI_HEADER_HEIGHT 44
#define DISPLAY_UI_PAGE_MARGIN   10
#define DISPLAY_UI_GAP           8
#define DISPLAY_UI_RADIUS        8
#define DISPLAY_UI_MIN_TAP       44
