#pragma once

#include "sdkconfig.h"

#include "app_config.h"
#include "media_tuning.h"

#ifndef APP_CONFIG_WECHAT_VOIP_ENABLE
#define APP_CONFIG_WECHAT_VOIP_ENABLE 1
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE
#define APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE APP_CONFIG_DEVICE_BINDING_API_BASE
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_API_BASE
#define APP_CONFIG_WECHAT_VOIP_API_BASE APP_CONFIG_DEVICE_BINDING_API_BASE
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_MQTT_URI
#define APP_CONFIG_WECHAT_VOIP_MQTT_URI APP_CONFIG_DEVICE_BINDING_MQTT_URI
#endif

#define WECHAT_VOIP_VERSION_RELEASE     0
#define WECHAT_VOIP_VERSION_DEVELOPMENT 1
#define WECHAT_VOIP_VERSION_TRIAL       2

#ifndef APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE
#define APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE WECHAT_VOIP_VERSION_RELEASE
#endif

#if APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE < WECHAT_VOIP_VERSION_RELEASE || \
    APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE > WECHAT_VOIP_VERSION_TRIAL
#error "APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE must be 0, 1, or 2"
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DEBUG_LOG
#define APP_CONFIG_WECHAT_VOIP_DEBUG_LOG 0
#endif

/*
 * Request the service's standard 640x480 landscape MJPEG rendition. These
 * protocol values remain independent from the physical 480x320 LCD.
 */
#define APP_CONFIG_WECHAT_VOIP_SCREEN_WIDTH  640
#define APP_CONFIG_WECHAT_VOIP_SCREEN_HEIGHT 480

#ifndef APP_CONFIG_WECHAT_VOIP_CAMERA_ROTATION
/* Protocol UI metadata only: WeChat rotates the published camera view.
 * Keep the local YUV420 -> H264 frame path byte-for-byte unchanged. */
#define APP_CONFIG_WECHAT_VOIP_CAMERA_ROTATION 270
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_OBJECT_FIT
/*
 * ThingConnect accepts only "fill" or "contain" for this protocol field.
 * Preserve the complete picture in the WeChat UI. The P4 downlink renderer is
 * independent: it uses one centered cover crop to map adaptive JPEG frames to
 * the fixed 480x320 panel without non-uniform stretching.
 */
#define APP_CONFIG_WECHAT_VOIP_OBJECT_FIT "contain"
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_VIDEO_WIDTH
#define APP_CONFIG_WECHAT_VOIP_VIDEO_WIDTH APP_MEDIA_WECHAT_VIDEO_WIDTH
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_VIDEO_HEIGHT
#define APP_CONFIG_WECHAT_VOIP_VIDEO_HEIGHT APP_MEDIA_WECHAT_VIDEO_HEIGHT
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_UP_VIDEO_MEDIA
#define APP_CONFIG_WECHAT_VOIP_UP_VIDEO_MEDIA "h264"
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_DOWN_VIDEO_MEDIA
#define APP_CONFIG_WECHAT_VOIP_DOWN_VIDEO_MEDIA "mjpeg"
#endif

#define WECHAT_VOIP_DEVICE_API_BASE APP_CONFIG_WECHAT_VOIP_DEVICE_API_BASE
#define WECHAT_VOIP_API_BASE APP_CONFIG_WECHAT_VOIP_API_BASE
#define WECHAT_VOIP_MQTT_URI APP_CONFIG_WECHAT_VOIP_MQTT_URI
#define WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE APP_CONFIG_WECHAT_VOIP_ACTIVE_CALL_VERSION_TYPE
#define WECHAT_VOIP_DEBUG_LOG APP_CONFIG_WECHAT_VOIP_DEBUG_LOG
#define WECHAT_VOIP_LOCAL_VIDEO_ENABLE APP_CONFIG_WECHAT_VOIP_LOCAL_VIDEO_ENABLE
#define WECHAT_VOIP_REMOTE_VIDEO_ENABLE CONFIG_APP_WECHAT_VOIP_REMOTE_VIDEO_ENABLE
#define WECHAT_VOIP_SCREEN_WIDTH APP_CONFIG_WECHAT_VOIP_SCREEN_WIDTH
#define WECHAT_VOIP_SCREEN_HEIGHT APP_CONFIG_WECHAT_VOIP_SCREEN_HEIGHT
#define WECHAT_VOIP_CAMERA_ROTATION APP_CONFIG_WECHAT_VOIP_CAMERA_ROTATION
#define WECHAT_VOIP_OBJECT_FIT APP_CONFIG_WECHAT_VOIP_OBJECT_FIT
#define WECHAT_VOIP_VIDEO_WIDTH APP_CONFIG_WECHAT_VOIP_VIDEO_WIDTH
#define WECHAT_VOIP_VIDEO_HEIGHT APP_CONFIG_WECHAT_VOIP_VIDEO_HEIGHT
#define WECHAT_VOIP_UP_VIDEO_MEDIA APP_CONFIG_WECHAT_VOIP_UP_VIDEO_MEDIA
#define WECHAT_VOIP_DOWN_VIDEO_MEDIA APP_CONFIG_WECHAT_VOIP_DOWN_VIDEO_MEDIA
