#pragma once

#ifndef APP_CONFIG_WIFI_ENABLE
#define APP_CONFIG_WIFI_ENABLE 1
#endif

#ifndef APP_CONFIG_WIFI_SSID
#define APP_CONFIG_WIFI_SSID ""
#endif

#ifndef APP_CONFIG_WIFI_PASSWORD
#define APP_CONFIG_WIFI_PASSWORD ""
#endif

#ifndef APP_CONFIG_WIFI_AUTO_CONNECT
#define APP_CONFIG_WIFI_AUTO_CONNECT 1
#endif

#ifndef APP_CONFIG_WIFI_FALLBACK_DNS_IPV4
#define APP_CONFIG_WIFI_FALLBACK_DNS_IPV4 "223.5.5.5"
#endif

#ifndef APP_CONFIG_OTA_DEFAULT_URL
#define APP_CONFIG_OTA_DEFAULT_URL "https://tirtc-device-ota.tange365.com"
#endif

#ifndef APP_CONFIG_RTC_ENABLE
#define APP_CONFIG_RTC_ENABLE 1
#endif

#ifndef APP_CONFIG_RTC_SERVICE_ENDPOINT
#define APP_CONFIG_RTC_SERVICE_ENDPOINT "https://ep-tirtc.tange365.com"
#endif

#ifndef APP_CONFIG_RTC_DEVICE_ID
#define APP_CONFIG_RTC_DEVICE_ID ""
#endif

#ifndef APP_CONFIG_RTC_DEVICE_SECRET_KEY
#define APP_CONFIG_RTC_DEVICE_SECRET_KEY ""
#endif

#ifndef APP_CONFIG_RTC_REMOTE_DEVICE_ID
#define APP_CONFIG_RTC_REMOTE_DEVICE_ID ""
#endif

#ifndef APP_CONFIG_RTC_REMOTE_DEVICE_SECRET_KEY
#define APP_CONFIG_RTC_REMOTE_DEVICE_SECRET_KEY ""
#endif

#ifndef APP_CONFIG_RTC_TOKEN_ACCESS_ID
#define APP_CONFIG_RTC_TOKEN_ACCESS_ID ""
#endif

#ifndef APP_CONFIG_RTC_TOKEN_SECRET_KEY
#define APP_CONFIG_RTC_TOKEN_SECRET_KEY ""
#endif

#ifndef APP_CONFIG_RTC_TOKEN_SUBJECT
#define APP_CONFIG_RTC_TOKEN_SUBJECT ""
#endif

#ifndef APP_CONFIG_RTC_TOKEN_TTL_SECONDS
#define APP_CONFIG_RTC_TOKEN_TTL_SECONDS 300U
#endif

#ifndef APP_CONFIG_AI_CHAT_ENABLE
#define APP_CONFIG_AI_CHAT_ENABLE 1
#endif

#ifndef APP_CONFIG_AI_CHAT_USER_ID
#define APP_CONFIG_AI_CHAT_USER_ID "user-001"
#endif

#ifndef APP_CONFIG_AI_CHAT_ROLE_ID
#define APP_CONFIG_AI_CHAT_ROLE_ID ""
#endif

#ifndef CONFIG_APP_AI_CHAT_VIDEO_ENABLE
#define CONFIG_APP_AI_CHAT_VIDEO_ENABLE 1
#endif

#ifndef APP_CONFIG_AI_CHAT_VIDEO_ENABLE
#define APP_CONFIG_AI_CHAT_VIDEO_ENABLE CONFIG_APP_AI_CHAT_VIDEO_ENABLE
#endif

#ifndef CONFIG_APP_AUDIO_AEC_ENABLE
#define CONFIG_APP_AUDIO_AEC_ENABLE 0
#endif

#ifndef APP_CONFIG_AUDIO_AEC_ENABLE
#define APP_CONFIG_AUDIO_AEC_ENABLE CONFIG_APP_AUDIO_AEC_ENABLE
#endif

#ifndef APP_CONFIG_AUDIO_AEC_REF_DELAY_MS
/* Used only when the codec-synchronous playback reference is unavailable. */
#define APP_CONFIG_AUDIO_AEC_REF_DELAY_MS 80U
#endif

#ifndef CONFIG_APP_WECHAT_VOIP_LOCAL_VIDEO_ENABLE
#define CONFIG_APP_WECHAT_VOIP_LOCAL_VIDEO_ENABLE 0
#endif

#ifndef APP_CONFIG_WECHAT_VOIP_LOCAL_VIDEO_ENABLE
#define APP_CONFIG_WECHAT_VOIP_LOCAL_VIDEO_ENABLE CONFIG_APP_WECHAT_VOIP_LOCAL_VIDEO_ENABLE
#endif

#ifndef APP_CONFIG_DEVICE_BINDING_ENABLE
#define APP_CONFIG_DEVICE_BINDING_ENABLE 1
#endif

#ifndef APP_CONFIG_THING_SERVICE_DISCOVERY_URL
#define APP_CONFIG_THING_SERVICE_DISCOVERY_URL "https://ep-open.tangeopen.com/services"
#endif

#ifndef APP_CONFIG_DEVICE_BINDING_API_BASE
#define APP_CONFIG_DEVICE_BINDING_API_BASE "https://srv-open.tangeopen.com"
#endif

#ifndef APP_CONFIG_DEVICE_BINDING_PORTAL_URL
#define APP_CONFIG_DEVICE_BINDING_PORTAL_URL "https://demo-open.tange-ai.com/devices"
#endif

#ifndef APP_CONFIG_DEVICE_BINDING_MQTT_URI
#define APP_CONFIG_DEVICE_BINDING_MQTT_URI "mqtts://mqtt-open.tangeopen.com:8883"
#endif

#ifndef APP_CONFIG_DEVICE_BINDING_WAIT_TIMEOUT_MS
#define APP_CONFIG_DEVICE_BINDING_WAIT_TIMEOUT_MS 180000U
#endif

#ifndef CONFIG_APP_DEBUG_SCREEN_SERVER_ENABLE
#define CONFIG_APP_DEBUG_SCREEN_SERVER_ENABLE 0
#endif

#ifndef APP_CONFIG_DEBUG_SCREEN_SERVER_ENABLE
#define APP_CONFIG_DEBUG_SCREEN_SERVER_ENABLE CONFIG_APP_DEBUG_SCREEN_SERVER_ENABLE
#endif
