#!/usr/bin/env python3
"""Generate native-size LVGL home assets from the checked-in Figma PNG exports."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
IMAGE_DIR = ROOT / "main" / "ui" / "image"
OUTPUT = ROOT / "main" / "ui" / "home_assets.c"

ASSETS = (
    ("home_icon_view.png", "home_icon_view_img", (40, 40)),
    ("home_icon_call.png", "home_icon_call_img", (40, 40)),
    ("home_icon_wechat.png", "home_icon_wechat_img", (40, 40)),
    ("home_icon_ai.png", "home_icon_ai_img", (40, 40)),
    ("home_icon_settings.png", "home_icon_settings_img", (40, 40)),
    ("home_text_title.png", "home_text_title_img", (78, 20)),
    ("home_text_view.png", "home_text_view_img", (39, 19)),
    ("home_text_view_desc.png", "home_text_view_desc_img", (55, 14)),
    ("home_text_call.png", "home_text_call_img", (38, 19)),
    ("home_text_call_desc.png", "home_text_call_desc_img", (61, 15)),
    ("home_text_wechat.png", "home_text_wechat_img", (79, 19)),
    ("home_text_wechat_desc.png", "home_text_wechat_desc_img", (61, 15)),
    ("home_text_ai.png", "home_text_ai_img", (59, 19)),
    ("home_text_ai_desc.png", "home_text_ai_desc_img", (89, 15)),
    ("home_text_settings.png", "home_text_settings_img", (39, 19)),
    ("home_text_settings_desc.png", "home_text_settings_desc_img", (86, 15)),
)


def encode_rgb565a8(image: Image.Image) -> bytes:
    encoded = bytearray()
    rgba = image.convert("RGBA")
    pixels = rgba.load()
    for y in range(rgba.height):
        for x in range(rgba.width):
            red, green, blue, alpha = pixels[x, y]
            rgb565 = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
            encoded.extend((rgb565 >> 8, rgb565 & 0xFF, alpha))
    return bytes(encoded)


def emit_byte_array(data: bytes) -> list[str]:
    lines: list[str] = []
    for offset in range(0, len(data), 24):
        chunk = data[offset : offset + 24]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return lines


def generate_source() -> str:
    lines = [
        '#include "home_assets.h"',
        "",
        "/* Generated by tools/generate_home_assets.py from native Figma exports. */",
        "",
    ]

    for filename, symbol, expected_size in ASSETS:
        path = IMAGE_DIR / filename
        with Image.open(path) as image:
            if image.size != expected_size:
                raise ValueError(
                    f"{path.relative_to(ROOT)} is {image.size[0]}x{image.size[1]}, "
                    f"expected {expected_size[0]}x{expected_size[1]}"
                )
            width, height = image.size
            encoded = encode_rgb565a8(image)

        map_symbol = f"{symbol}_map"
        lines.append(
            f"static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t {map_symbol}[] = {{"
        )
        lines.extend(emit_byte_array(encoded))
        lines.extend(
            [
                "};",
                "",
                f"const lv_img_dsc_t {symbol} = {{",
                "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,",
                "    .header.always_zero = 0,",
                "    .header.reserved = 0,",
                f"    .header.w = {width},",
                f"    .header.h = {height},",
                f"    .data_size = {width} * {height} * LV_IMG_PX_SIZE_ALPHA_BYTE,",
                f"    .data = {map_symbol},",
                "};",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
    args = parser.parse_args()

    generated = generate_source()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            raise SystemExit(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
        return

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
