#!/usr/bin/env python3
"""Size the supplied phone icon for the P4 shortcut without runtime decoding."""

from pathlib import Path

from PIL import Image, ImageOps

from lvgl_image import encode_rgb565a8, emit_byte_array


ROOT = Path(__file__).resolve().parents[1]
COMPONENT = ROOT / "components" / "starter_product"
SOURCE = COMPONENT / "assets" / "phone_shortcut.png"
OUTPUT = COMPONENT / "src" / "starter_product_p4_phone.inc"
SIZE = (42, 42)  # Physical pixels, centred in the 48 x 42 px button.


def main() -> None:
    with Image.open(SOURCE) as source:
        image = ImageOps.fit(source.convert("RGBA"), SIZE, Image.Resampling.LANCZOS)
        data = encode_rgb565a8(image)

    lines = [
        "/* Generated by tools/generate_phone_shortcut.py from assets/phone_shortcut.png.",
        " * RGB565 (byte-swapped) + alpha; immutable pixels stay in flash. */",
        "#if LV_COLOR_DEPTH != 16 || !LV_COLOR_16_SWAP",
        '#error "P4 phone shortcut requires the configured byte-swapped RGB565 format"',
        "#endif",
        "",
        "static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t p4_phone_shortcut_pixels[] = {",
        *emit_byte_array(data),
        "};",
        "",
        "static const lv_img_dsc_t p4_phone_shortcut_image = {",
        "    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        f"    .header.w = {SIZE[0]},",
        f"    .header.h = {SIZE[1]},",
        "    .data_size = sizeof(p4_phone_shortcut_pixels),",
        "    .data = p4_phone_shortcut_pixels,",
        "};",
        "",
    ]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
